### ISSUE TITLE
Small description for spot

### ISSUE THREAD

**Issue by M8825** [M8825/Parkly#14]
We need a short description of a spot. It will require DB schema modification and index card design modification.

- Short description

**Comment by JosephBergmann** [comment]
15 minutes to 2 hours

**Comment by M8825** [comment]
@JosephBergmann, any updates on it, Mr. Joseph?

**Comment by JosephBergmann** [comment]
I hope to be done with this by 10 tonight

**Comment by M8825** [comment]
I think you fixed this issue with recent a  pull request @JosephBergmann. Probably you forgot to update the notes here.  please confirm.

**Comment by JosephBergmann** [comment]
This issue was resolved with last night's pull request
