### ISSUE TITLE
User should have phone number

### ISSUE THREAD

**Issue by M8825** [M8825/Parkly#15]
Please update front and backend for the info @JosephBergmann @stivenkang

**Comment by stivenkang** [comment]
Will include phone number into sign up form by 6pm.

**Comment by M8825** [comment]
Steven, did you have a chance to update the form for this change? @stivenkang 

> Will include phone number into sign up form by 6pm.

**Comment by stivenkang** [comment]
Was not able to update the form before 6pm. Will try and finish the css for create new post page asap and then will work on adding the phone number hopefully in the next 2 hours.

**Comment by stivenkang** [comment]
Phone number has been included into sign up modal with errors. Issue complete
