### ISSUE TITLE
DB spot "Title" column

### ISSUE THREAD

**Issue by stivenkang** [M8825/Parkly#16]
Need to create a "Title" column in the spot db so spot owners can put a personal title for the spot.

**Comment by M8825** [comment]
Can you please give me an example of title for a spot?

**Comment by stivenkang** [comment]
It would generally be anything the user wants to say about their spot but a general example would be:

"Clean parking spot in building's underground parking lot with easy access."

or

"Spacious driveway parking spot.

or something along those lines.

**Comment by JosephBergmann** [comment]
I hope to be done with this by 10 tonight

**Comment by M8825** [comment]
@JosephBergmann please confirm that you fixed it so I can close it. Thanks

**Comment by JosephBergmann** [comment]
The backend part of this issue was resolved with last night's pull request

**Comment by stivenkang** [comment]
Create spot form contains a Title input bar. Frontend complete.
