### ISSUE TITLE
needed more data

### ISSUE THREAD

**Issue by Yenleespace** [M8825/Parkly#29]
Please consider adding additional data to the seed file.
When adding new data, please make sure to take into account the proper use of capitalization and let me know once you start.

**Comment by JosephBergmann** [comment]
Database has been reseeded. Please let me know if you notice any further problems with capitalization , as well as spots without an owner and the like. Thank you for your patience.

**Comment by M8825** [comment]
@Yenleespace, Can we close this issue, or do we need to talk more about it?

**Comment by Yenleespace** [comment]
closed.
