### ISSUE TITLE
Raiting hard coded

### ISSUE THREAD

**Issue by M8825** [M8825/Parkly#31]
Rating is hardcoded in the database and front-end level and needs to be fixed. Specifically, it should be dynamically updated and inserted.

**Comment by JosephBergmann** [comment]
Thank you for bringing this to my attention. Are you not able to update this using the patch function?

**Comment by M8825** [comment]
We still don't have update form/functionality on our frontend

**Comment by M8825** [comment]
@Yenleespace I believe this issue is resolved, right?

**Comment by Yenleespace** [comment]
yes!
