### ISSUE TITLE
Data for spot is not consistant

### ISSUE THREAD

**Issue by M8825** [M8825/Parkly#32]
Spot data is not consistent in the database, we need to have a title, band address for every spot and all columns should be there and null false

**Comment by JosephBergmann** [comment]
Could you elaborate a little on this issue? I've added a spots seed to the database and reseeded so that should have resolved the issue for now. We can have a discussion on what I think constitutes as a null false constraint if you'd like.

**Comment by JosephBergmann** [comment]
I'm fairly certain my latest pull request resolves this issue, but again please get back to me on whether or not you think certain fields should be nullable. Thank you

**Comment by M8825** [comment]
Done
