### ISSUE TITLE
search bar needed

### ISSUE THREAD

**Issue by Yenleespace** [M8825/Parkly#33]
search bar model needed for splash page, indexing page

**Comment by M8825** [comment]
I'll work on that after closing majority of the issues

**Comment by Yenleespace** [comment]
mern stack elasticsearch example is required.

**Comment by Yenleespace** [comment]
frontend(user input accepted)-> backend(request data to db using elasticsearch)-> database->backend(data received from db)->frontend(result is showed)

**Comment by M8825** [comment]
I think it can be simplified to a point were we just send requests for all parking spots to a database, and then we filter results in thunk action based on search parameters before we add it to a state.

**Comment by M8825** [comment]
I'm not sure why we can't use bootstrap for just a visual representation of the search bar and checkmark filters. Can you elaborate more on that?

**Comment by Yenleespace** [comment]
bootstrap works. Let's discuss pricing range and please reseed db various pricing.

**Comment by M8825** [comment]
@Yenleespace Great work. Sounds good.
@JosephBergmann, whenever you have a chance.

**Comment by M8825** [comment]
Done
