### ISSUE TITLE
rating is not float

### ISSUE THREAD

**Issue by Yenleespace** [M8825/Parkly#37]

**Comment by JosephBergmann** [comment]
Thank you for bringing this to my attention. I'll do a little bit of testing and get back to you on what can be done.

**Comment by JosephBergmann** [comment]
Hello, just getting back to you to tell you that at least in postman I was able to make a spot with a float rating. Ratings are javascript Number objects. Please get back to me letting me know what context you were having difficulty using floats and I'll see what I can do. Thanks

**Comment by Yenleespace** [comment]
closed.
