### ISSUE TITLE
understandable title  for spot. NY/NJ only address.

### ISSUE THREAD

**Issue by Yenleespace** [M8825/Parkly#38]

**Comment by JosephBergmann** [comment]
Thank you for bringing this to my attention. Malkhaz went through the database and changed this himself. However I'll update the seed file itself tonight, so that future reseeds aren't Lorem Ipsum.

**Comment by M8825** [comment]
Pick 2 zip codes in NY, like 10028 and any zip code in Jersey City and populate 15-15 spots in DB

**Comment by JosephBergmann** [comment]
I like this idea; should be easy to do with a random number generator. My current plan is to finish the reseed of the database by noon Thursday, though please tell me if this is more urgent.

**Comment by M8825** [comment]
@JosephBergmann Any updates?

**Comment by JosephBergmann** [comment]
Yes the updated seed file resolves this specific issue. The seed file will have a more robust upgrade in the future.
