### ISSUE TITLE
please upload profile image(png/jpg file), linkdin, Wellfund, github links for Contact us page by Thursday.

### ISSUE THREAD

**Issue by Yenleespace** [M8825/Parkly#79]

**Comment by M8825** [comment]
- [GitHub](https://github.com/M8825)
- [LinkedIn](https://www.linkedin.com/in/malkhaz-mamulashvili-703a97208/)
- [wellfound](https://angel.co/profile/edit/overview):

**Comment by M8825** [comment]
@JosephBergmann, Any updates on this Mr. Joseph?

**Comment by JosephBergmann** [comment]
https://www.linkedin.com/in/joseph-bergmann-06855a268/
https://www.github.com/josephbergmann/

**Comment by M8825** [comment]
@Yenleespace Do you still missing that information?

**Comment by M8825** [comment]
@JosephBergmann I think she also needs your profile picture.

**Comment by Yenleespace** [comment]
@M8825 please check you wellfound link again ex) https://angel.co/u/yenleespace
